#!/usr/bin/env python3

import os
import sys
import csv
import argparse
from glob import glob

import logging

logging.basicConfig(level=logging.INFO)


def chunk_list(data, chunk_size):
    """Yield successive chunk_size-sized chunks from data."""
    for i in range(0, len(data), chunk_size):
        yield data[i:i + chunk_size]
        

def main():
    parser = argparse.ArgumentParser(description='Generate a CSV samplesheet for VIRify using the output of genome '
                                                 'catalogue pipeline.')
    parser.add_argument('--species-catalogue-folder', required=True,
                        help='Full path to the species_catalogue folder (inside the main output directory '
                             'generated by genome catalogue pipeline')
    parser.add_argument('--output', default='virify_samplesheet.csv', help='Output CSV filename (default: '
                                                                           'virify_samplesheet.csv)')
    parser.add_argument('--chunk-size', type=int, default=4000,
                        help='Maximum number of records per CSV. Default: 4000')
    args = parser.parse_args()

    base_dir = args.species_catalogue_folder
    output_csv_base = args.output
    chunk_size = args.chunk_size

    header = ['id', 'assembly', 'fastq_1', 'fastq_2', 'proteins']
    rows = []

    # Traverse two levels down
    for mid_subfolder_level in os.listdir(base_dir):
        mid_subfolder_path = os.path.join(base_dir, mid_subfolder_level)  # This is one level above species rep folders
        if os.path.isdir(mid_subfolder_path):
            for species_folder in os.listdir(mid_subfolder_path):
                species_folder_path = os.path.join(mid_subfolder_path, species_folder)
                genome_path = os.path.join(species_folder_path, 'genome')

                if os.path.isdir(genome_path):
                    fna_file = glob(os.path.join(genome_path, '*.fna'))[0]

                    if fna_file:
                        row = [
                            species_folder,
                            os.path.abspath(fna_file),
                            '',
                            '',
                            ''
                        ]
                        rows.append(row)
                    else:
                        logging.error(f"MISSING THE GENOME FILE: {genome_path}")
                        sys.exit()

    # Handle chunking
    chunk_index = 1
    for chunk in chunk_list(rows, chunk_size):
        chunk_filename = output_csv_base.replace('.csv', f'_chunk_{chunk_index}.csv')
        with open(chunk_filename, 'w', newline='') as csvfile:
            writer = csv.writer(csvfile)
            writer.writerow(header)
            writer.writerows(chunk)
        logging.info(f"CSV chunk {chunk_index} written to '{chunk_filename}'")
        chunk_index += 1


if __name__ == '__main__':
    main()
