#!/usr/bin/env python3

import os
import sys
import csv
import argparse
from glob import glob
from tqdm import tqdm

import logging

logging.basicConfig(level=logging.INFO)

def chunk_list(data, chunk_size):
    """Yield successive chunk_size-sized chunks from data."""
    for i in range(0, len(data), chunk_size):
        yield data[i:i + chunk_size]

def main():
    parser = argparse.ArgumentParser(description='Generate a CSV samplesheet for the mobilome annotation pipeline using '
                                                 'the output of genome catalogue pipeline and VIRify.')
    parser.add_argument('--species-catalogue-folder', required=True,
                        help='Path to the species_catalogue folder (inside the main output directory '
                             'generated by genome catalogue pipeline')
    parser.add_argument('--virify-folder', required=True,
                        help='Path to the completed VIRify output folder')
    parser.add_argument('--outfile', default='map_samplesheet.csv', help='Output CSV filename')
    parser.add_argument('--annotation-manifest', '-m', default='map_manifest.csv', help='Annotation manifest filename')
    parser.add_argument('--chunk-size', type=int, default=20, help='Maximum number of records per CSV. Default: 20')
    args = parser.parse_args()
    
    count_virify_gff = 0
    chunk_size = args.chunk_size

    for folder in [args.species_catalogue_folder, args.virify_folder]:
        if not os.path.exists(folder):
            logging.critical('The specified input folder does not exist: {}'.format(folder))
            sys.exit(1)
            
    # Get a list of genomes in the VIRify output folder
    mgyg_folders = [
        name for name in os.listdir(args.virify_folder)
        if os.path.isdir(os.path.join(args.virify_folder, name)) and name.startswith("MGYG")
    ]

    header = ['sample', 'assembly', 'proteins_gff', 'proteins_faa', 'virify_gff']
    annotation_manifest_header = ['sample', 'amrfinder_tsv', 'antismash_gff', 'gecco_gff', 'sanntis_gff']
    samplesheet_rows, manifest_rows = [], []

    for accession in tqdm(sorted(mgyg_folders)):
        genome_folder_path = os.path.join(args.species_catalogue_folder, accession[:-2], accession, "genome")

        # standard samplesheet
        assembly = os.path.abspath(glob(os.path.join(genome_folder_path, '*.fna'))[0])
        proteins_gff = os.path.abspath(glob(os.path.join(genome_folder_path, '*_annotated.gff'))[0])
        proteins_faa = os.path.abspath(glob(os.path.join(genome_folder_path, '*.faa'))[0])
        virify_gff_path = os.path.abspath(os.path.join(args.virify_folder, accession, "08-final", "gff", 
                                                    f"{accession}_virify.gff"))
        virify_gff_record = virify_gff_path if os.path.exists(virify_gff_path) else ""
        if virify_gff_record:
            count_virify_gff += 1
        row = [accession, assembly, proteins_gff, proteins_faa, virify_gff_record]
        samplesheet_rows.append(row)
        # samplesheet_writer.writerow(row)

        # annotation manifest
        armfinderplus_tsv = os.path.abspath(glob(os.path.join(genome_folder_path, '*_amrfinderplus.tsv'))[0])
        antismash_gff = os.path.abspath(glob(os.path.join(genome_folder_path, '*_antismash.gff'))[0])
        gecco_gff = os.path.abspath(glob(os.path.join(genome_folder_path, '*_gecco.gff'))[0])
        sanntis_gff = os.path.abspath(glob(os.path.join(genome_folder_path, '*_sanntis.gff'))[0])
        row = [accession, armfinderplus_tsv, antismash_gff, gecco_gff, sanntis_gff]
        manifest_rows.append(row)

    # Handle chunking
    chunk_index = 1
    for chunk in chunk_list(samplesheet_rows, chunk_size):
        samplesheet_chunk_filename = args.outfile.replace('.csv', f'_chunk_{chunk_index}.csv')
        with open(samplesheet_chunk_filename, "w", newline='') as s_out:
            samplesheet_writer = csv.writer(s_out)
            samplesheet_writer.writerow(header)
            samplesheet_writer.writerows(chunk)
        chunk_index += 1

    chunk_index = 1
    for chunk in chunk_list(manifest_rows, chunk_size):
        manifest_chunk_filename = args.annotation_manifest.replace('.csv', f'_chunk_{chunk_index}.csv')
        with open(manifest_chunk_filename, 'w', newline='') as am_out:
            am_writer = csv.writer(am_out)
            am_writer.writerow(annotation_manifest_header)
            am_writer.writerows(chunk)
        chunk_index += 1
    
    logging.info(f"Finished writing {len(mgyg_folders)} records. {count_virify_gff} records have a VIRify GFF.")


if __name__ == '__main__':
    main()