[tool.pytest.ini_options]
pythonpath = [".", "tests"]
python_files = ["test_*.py"]

[tool.ruff]
line-length = 110

[tool.isort]
profile = "black"

[tool.back]
line-length = 110
experimental-string-processing = true