name: Python unit testing

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v3
    - name: 🐍 - Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        pip install -U -r requirements-test.txt
    - name: Testing
      run: |
        PYTHONPATH="$PYTHONPATH:bin:helpers/database-import-scripts/uniprot" pytest
