#!/usr/bin/env python3
"""
End-to-end tests for replace_species_representative.main.

Each test calls main() with real input files from tests/fixtures/e2e/ and
validates the two output files (clusters split + report TSV) against
pre-computed SHA-256 checksums of the known outputs.

Fixture layout
--------------
tests/fixtures/e2e_replace_species_representative/
  cluster_split.txt          – previous-catalogue cluster split file (4 species)
  checkm2.csv                – completeness / contamination for all genomes
  assembly_stats.tsv         – N50 / length / contig count for all genomes
  isolates.txt               – isolate weight file (MGYG000000009 is an isolate)
  remove_list.txt            – two genomes to remove (MGYG000000007, MGYG000000003)
  remove_list_empty.txt      – empty remove list (for no-op / reannotation scenario)
  new_strains.tsv            – two new-strain placements
  repeat_strains.tsv         – two repeat-strain placements
  new_species_split.txt      – two pre-existing new-species clusters to prepend
  golden_clusters_split.txt          – expected clusters split output for the full run
  golden_cluster_rep_changes_report.tsv  – expected report output for the full run
  golden_noop_clusters_split.txt         – expected clusters split output for no-op run
  golden_noop_cluster_rep_changes_report.tsv – expected report for no-op run

Scenarios covered
-----------------
1. full_run     – remove + add new/repeat strains + new-species prepend + isolate
                  promotion + quality-based rep replacement
2. noop_run     – no removals, no additions, no CheckM2 switch → input file is
                  copied unchanged; report is empty
3. checkm2_only – CheckM2 switch with no other changes → all clusters are
                  reassessed; rep stays the same when it is already best
"""

import hashlib
import os
import shutil
import tempfile
import unittest

from bin.replace_species_representative import main  

from pathlib import Path

FIXTURES = Path(__file__).resolve().parent / "fixtures" / "e2e_replace_species_representative"


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def sha256(path: str) -> str:
    """Return the hex SHA-256 digest of a file."""
    h = hashlib.sha256()
    with open(path, "rb") as fh:
        for chunk in iter(lambda: fh.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


def fixture(name: str) -> str:
    """Return the absolute path to a fixture file."""
    return os.path.join(FIXTURES, name)


# ---------------------------------------------------------------------------
# Golden checksums (generated by running the script against the fixture files)
# ---------------------------------------------------------------------------

GOLDEN = {
    "full_run": {
        "clusters": "586a64f68b70520a76b8ad74437bb34f088647b423a121dd4953118eeb7fad71",
        "report":   "209349a79635783453aeddc5e7d66db3169bbc2f2949ce539e42565b5a9aa2c7",
    },
    "noop": {
        "clusters": "98099c82c73123e52a14a2dd89911bb8c3c9e30b11489c8660115515fea0a395",
        "report":   "806dd81338349c947d7949c74625ee2146fed3729e770185e597313cab920ae7",
    },
}

# ---------------------------------------------------------------------------
# Base test class
# ---------------------------------------------------------------------------


class E2ETestBase(unittest.TestCase):
    """Creates a temporary output directory for each test and cleans it up."""

    def setUp(self):
        self.tmp_dir = tempfile.mkdtemp(prefix="test_replace_rep_")
        self.output_prefix = os.path.join(self.tmp_dir, "out")

    def tearDown(self):
        shutil.rmtree(self.tmp_dir, ignore_errors=True)

    # ------------------------------------------------------------------
    # Convenience properties for output file paths
    # ------------------------------------------------------------------

    @property
    def clusters_file(self) -> str:
        return f"{self.output_prefix}_clusters_split.txt"

    @property
    def report_file(self) -> str:
        return f"{self.output_prefix}_cluster_rep_changes_report.tsv"

    # ------------------------------------------------------------------
    # Assertion helpers
    # ------------------------------------------------------------------

    def assertFileMatchesGolden(self, actual_path: str, expected_checksum: str, label: str):
        self.assertTrue(
            os.path.exists(actual_path),
            msg=f"{label}: output file not created at {actual_path}",
        )
        actual_checksum = sha256(actual_path)
        self.assertEqual(
            actual_checksum,
            expected_checksum,
            msg=(
                f"{label}: checksum mismatch.\n"
                f"  expected : {expected_checksum}\n"
                f"  actual   : {actual_checksum}\n"
                f"  file     : {actual_path}"
            ),
        )


# ---------------------------------------------------------------------------
# Test cases
# ---------------------------------------------------------------------------

class TestE2EFullRun(E2ETestBase):
    """
    Full-pipeline scenario:
    - MGYG000000007 (species rep) and MGYG000000003 (member) are removed
    - 2 new strains are added; MGYG000000009 is an isolate and displaces the rep
    - 2 repeat strains are added; quality-based evaluation decides which are kept
    - New-species split file is prepended to the output
    """

    def test_clusters_split_checksum(self):
        main(
            cluster_split_file=fixture("cluster_split.txt"),
            output_prefix=self.output_prefix,
            assembly_stats_file=fixture("assembly_stats.tsv"),
            isolates_file=fixture("isolates.txt"),
            checkm_file=fixture("checkm2.csv"),
            remove_list_file=fixture("remove_list.txt"),
            checkm2_switch=False,
            new_species_split_file=fixture("new_species_split.txt"),
            new_strain_file=fixture("new_strains.tsv"),
            repeat_strain_file=fixture("repeat_strains.tsv"),
        )
        self.assertFileMatchesGolden(
            self.clusters_file,
            GOLDEN["full_run"]["clusters"],
            label="full_run / clusters_split",
        )

    def test_report_tsv_checksum(self):
        main(
            cluster_split_file=fixture("cluster_split.txt"),
            output_prefix=self.output_prefix,
            assembly_stats_file=fixture("assembly_stats.tsv"),
            isolates_file=fixture("isolates.txt"),
            checkm_file=fixture("checkm2.csv"),
            remove_list_file=fixture("remove_list.txt"),
            checkm2_switch=False,
            new_species_split_file=fixture("new_species_split.txt"),
            new_strain_file=fixture("new_strains.tsv"),
            repeat_strain_file=fixture("repeat_strains.tsv"),
        )
        self.assertFileMatchesGolden(
            self.report_file,
            GOLDEN["full_run"]["report"],
            label="full_run / report_tsv",
        )

    def test_both_outputs_produced(self):
        """Sanity check: both output files must exist after a successful run."""
        main(
            cluster_split_file=fixture("cluster_split.txt"),
            output_prefix=self.output_prefix,
            assembly_stats_file=fixture("assembly_stats.tsv"),
            isolates_file=fixture("isolates.txt"),
            checkm_file=fixture("checkm2.csv"),
            remove_list_file=fixture("remove_list.txt"),
            checkm2_switch=False,
            new_species_split_file=fixture("new_species_split.txt"),
            new_strain_file=fixture("new_strains.tsv"),
            repeat_strain_file=fixture("repeat_strains.tsv"),
        )
        self.assertTrue(os.path.exists(self.clusters_file), "clusters split file missing")
        self.assertTrue(os.path.exists(self.report_file), "report TSV missing")


class TestE2ENoopRun(E2ETestBase):
    """
    Reannotation-only scenario: nothing is added or removed and CheckM2 switch
    is off.  main() should copy the input file unchanged and write an empty
    report header.
    """

    def _run(self):
        main(
            cluster_split_file=fixture("cluster_split.txt"),
            output_prefix=self.output_prefix,
            assembly_stats_file=fixture("assembly_stats.tsv"),
            isolates_file=fixture("isolates.txt"),
            checkm_file=fixture("checkm2.csv"),
            remove_list_file=fixture("remove_list_empty.txt"),
            checkm2_switch=False,
        )

    def test_clusters_split_checksum(self):
        self._run()
        self.assertFileMatchesGolden(
            self.clusters_file,
            GOLDEN["noop"]["clusters"],
            label="noop / clusters_split",
        )

    def test_report_tsv_checksum(self):
        self._run()
        self.assertFileMatchesGolden(
            self.report_file,
            GOLDEN["noop"]["report"],
            label="noop / report_tsv",
        )

    def test_clusters_file_is_unchanged_copy_of_input(self):
        """Output clusters file must be byte-for-byte identical to the input."""
        self._run()
        self.assertEqual(
            sha256(fixture("cluster_split.txt")),
            sha256(self.clusters_file),
            msg="No-op run: output clusters file differs from input",
        )

    def test_report_contains_only_header(self):
        """Report TSV for a no-op run should contain only the header row."""
        self._run()
        with open(self.report_file, "r", encoding="utf-8") as fh:
            lines = [l for l in fh.read().splitlines() if l.strip()]
        self.assertEqual(
            len(lines),
            1,
            msg=f"Expected 1 header line in no-op report, got {len(lines)}: {lines}",
        )


class TestE2ECheckm2Switch(E2ETestBase):
    """
    CheckM2 switch with no other changes: all clusters are re-evaluated for rep
    replacement. When the existing rep is already the highest-quality genome,
    no replacement should occur and the report should be empty except for the
    header.
    """

    def test_no_replacement_when_rep_is_best(self):
        """
        Cluster MGYG000000006 is a singleton with high quality; with no new
        genomes added, the checkm2_switch flag should not force any replacement.
        The report should contain only the TSV header row.
        """
        main(
            cluster_split_file=fixture("cluster_split.txt"),
            output_prefix=self.output_prefix,
            assembly_stats_file=fixture("assembly_stats.tsv"),
            isolates_file=fixture("isolates.txt"),
            checkm_file=fixture("checkm2.csv"),
            remove_list_file=fixture("remove_list_empty.txt"),
            checkm2_switch=True,
        )
        with open(self.report_file, "r", encoding="utf-8") as fh:
            lines = [l for l in fh.read().splitlines() if l.strip()]
        # Only the header; no replacements because current reps are already best
        self.assertEqual(
            len(lines),
            1,
            msg=f"Expected only header row; got {len(lines)} lines: {lines}",
        )

    def test_clusters_file_produced(self):
        main(
            cluster_split_file=fixture("cluster_split.txt"),
            output_prefix=self.output_prefix,
            assembly_stats_file=fixture("assembly_stats.tsv"),
            isolates_file=fixture("isolates.txt"),
            checkm_file=fixture("checkm2.csv"),
            remove_list_file=fixture("remove_list_empty.txt"),
            checkm2_switch=True,
        )
        self.assertTrue(
            os.path.exists(self.clusters_file),
            msg="clusters split file not produced for checkm2_switch=True run",
        )


if __name__ == "__main__":
    unittest.main()